name: Deploy

on: [push]

env:
  DOCKER_REPOSITORY: 'sdodson/su-covid-cron-function'
  DOCKER_BUILD_CONTEXT: 'src'
  DOCKERFILE_PATH: 'src/cron-function/Dockerfile'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: 'Deploy Docker Image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          path: ${{ env.DOCKER_BUILD_CONTEXT }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          tags: latest

      - name: 'Login to Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
