name: Deploy CRON Timer

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: 'su-covid-daily-cron'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/cron-function'
  PLAYWRIGHT_BROWSERS_PATH: '0'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: 'Install packages'
        run: 'cd src/cron-function && npm i'

      - name: 'Login to Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: 'Install Azure Function Core Tools'
        run: 'npm i -g azure-functions-core-tools@3'

      - name: 'Deploy Azure Function'
        run: 'cd src/cron-function && func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }}'
