name: Deploy

on:
  push:
    branches:
      - master

env:
  DOCKER_REPOSITORY: 'sdodson/su-covid-cron-function'
  DOCKER_BUILD_CONTEXT: 'src'
  DOCKERFILE_PATH: 'src/cron-function/Dockerfile'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Deploy Docker Image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          path: ${{ env.DOCKER_BUILD_CONTEXT }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          tags: latest
